apiVersion: v1
data:
  node-config.yaml: |
    apiVersion: v1
    authConfig:
      authenticationCacheSize: 1000
      authenticationCacheTTL: 5m
      authorizationCacheSize: 1000
      authorizationCacheTTL: 5m
    dnsBindAddress: 127.0.0.1:53
    dnsDomain: cluster.local
    dnsIP: 0.0.0.0
    dnsNameservers: null
    dnsRecursiveResolvConf: /etc/origin/node/resolv.conf
    dockerConfig:
      dockerShimRootDirectory: /var/lib/dockershim
      dockerShimSocket: /var/run/dockershim.sock
      execHandlerName: native
    enableUnidling: true
    imageConfig:
      format: satellite.home.nicknach.net:8888/openshift3/ose-${component}:${version}
      latest: false
    iptablesSyncPeriod: 30s
    kind: NodeConfig
    kubeletArguments:
      bootstrap-kubeconfig:
      - /etc/origin/node/bootstrap.kubeconfig
      cert-dir:
      - /etc/origin/node/certificates
      enable-controller-attach-detach:
      - 'true'
      feature-gates:
      - RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true,DevicePlugins=true
      node-labels:
      - node-role.kubernetes.io/compute=true
      - node-role.kubernetes.io/nvidia=true
      pod-manifest-path:
      - /etc/origin/node/pods
      rotate-certificates:
      - 'true'
    masterClientConnectionOverrides:
      acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
      burst: 40
      contentType: application/vnd.kubernetes.protobuf
      qps: 20
    masterKubeConfig: node.kubeconfig
    networkConfig:
      mtu: 1450
      networkPluginName: redhat/openshift-ovs-subnet
    proxyArguments:
      cluster-cidr:
      - 10.128.0.0/14
    servingInfo:
      bindAddress: 0.0.0.0:10250
      bindNetwork: tcp4
      clientCA: client-ca.crt
    volumeConfig:
      localQuota:
        perFSGroup: null
    volumeDirectory: /var/lib/origin/openshift.local.volumes
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: node-config-nvidia
  selfLink: /api/v1/namespaces/openshift-node/configmaps/node-config-compute
